PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX tate: <http://sparql.xyz/example/tate/>
PREFIX tsub: <http://sparql.xyz/example/tate/subject/>
PREFIX schema: <http://schema.org/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT 
 distinct ?decade
WHERE {
  # List of artworks
  SERVICE <x-sparql-anything:csv.headers=true,location=./collection/artwork_data.csv> {
    []  xyz:id ?id ; # ?id { _ x, _ c, _ v ,b,n }
		xyz:accession_number ?accId #;  # ?id { _ x, _ c, _ v ,b,n } ?accId { } [ A 1 ] , [ B 1 ]
        #xyz:title ?title; # [ A 1 T ] , [ B 1 T ]
		#xyz:thumbnailUrl ?thumbnail . # [ A 1 T B ] , [ B 1 T B ]
		.
  }
  #  BIND (IRI(CONCAT(STR(tate:), "artwork-", ?id )) AS ?artwork) .
  #  BIND (IRI(CONCAT(STR(tate:), "artist-", ?artistId )) AS ?artist) .
  BIND ( IF ( STRSTARTS( ?accId, "AR" ) ,
    LCASE(CONCAT( "ar/", SUBSTR( ?accId ,3 ,3), "/", ?accId, "-", ?id , ".json" )),
    LCASE(CONCAT( SUBSTR( ?accId ,1 , 1), "/", SUBSTR( ?accId ,2 , 3), "/" , ?accId, "-", ?id , ".json" ))
  ) AS ?filepath ) . # { ?id ?accId ?title ?thumbnail ?filepath }
  # JSON file with subjects
  BIND (IRI(CONCAT("x-sparql-anything:location=./collection/artworks/", ?filepath )) AS ?artworkMetadata ) .
   # { ?id ?accId ?title ?thumbnail ?filepath ?artworkMetadata }
  SERVICE ?artworkMetadata {
	  {
		  [] xyz:dateText ?year .
	  }
  } .
  filter (bound(?year)).
  bind ( replace( replace(?year, "c.", "") , "^[^0-9]*?([0-9]{3})?.*$", "$1") as ?decade)

#  bind (fx:String.substring(?year, 0, 3) as ?decade)
  # { ?id ?accId ?title ?thumbnail ?filepath ?artworkMetadata ?li2 ?subjectId }
} #GROUP BY ?id ?title ?thumbnail ?filepath