PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX fx:   <http://sparql.xyz/facade-x/ns/>
PREFIX xyz:  <http://sparql.xyz/facade-x/data/>
PREFIX tate: <http://sparql.xyz/example/tate/>
PREFIX tsub: <http://sparql.xyz/example/tate/subject/>


SELECT DISTINCT ?parentId ?parentName
WHERE {
  # JSON file with subjects
  BIND (IRI(CONCAT("x-sparql-anything:location=./collection/artworks/t/091/t09122-23226.json" )) AS ?artworkMetadata ) .
  SERVICE ?artworkMetadata { 
	  [] xyz:id ?parentId ; xyz:name ?parentName 
  } .
}


