PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX fx:   <http://sparql.xyz/facade-x/ns/>
PREFIX xyz:  <http://sparql.xyz/facade-x/data/>
PREFIX tate: <http://sparql.xyz/example/tate/>
PREFIX tsub: <http://sparql.xyz/example/tate/subject/>
PREFIX tart: <http://sparql.xyz/example/tate/artwork/>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT ?subjectId (COUNT(?artworkId) as ?count)
WHERE {
	SERVICE <x-sparql-anything:location=./subjects-artworks-id.csv,csv.headers=true> {
		[] xyz:subjectId ?subjectId ; xyz:artworkId ?artworkId .
	}
}
GROUP BY ?subjectId
ORDER BY DESC(?count)
#LIMIT 10
